baseURL: "https://johndmart.in/dissertation/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Dissertation
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
#        menu:
#            main:
#                - name: Archive
#                  url: archives
#                  weight: 5
#                - name: Search
#                  url: search/
#                  weight: 10
#                - name: Tags
#                  url: tags/
#                  weight: 10
#                - name: Categories
#                  url: categories/
#                  weight: 10

#    ar:
#        languagedirection: rtl
#        weight: 3
#        title: Arabic
#        homeInfoParams:
#            Title: "Hi there \U0001F44B"
#            Content: Welcome to RTL layout
#        taxonomies:
#          category: ARcategories
#          tag: ARtags
#          series: ARseries
#        menu:
#            main:
#                - name: ARTags
#                  url: artags
#                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "A dissertation on language, spatial agency bias, and online survey interfaces."
    author: John D. Martin III
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

#    profileMode:
#        enabled: false
#        title: Agree, Disagree, Agree: a dissertation by John D. Martin III
#        imageUrl: "#"
#        imageTitle: my image
#        # imageWidth: 120
#        # imageHeight: 120
#        buttons:
#            - name: Archives
#              url: archives
#            - name: Tags
#              url: tags

    homeInfoParams:
        Title: "Agree, Disagree, Agree: A dissertation project by John D. Martin III"
        Content: >
          ## Spatial orientation and online survey

          - This dissertation study looks at interactions between writing system direction and response category order in online survey.
            Visuo-spatial elements in online survey instruments may be subject to a form of interference called Spatial Agency Bias (SAB).
            This study investigates the effects of visuo-spatial incongruency between directionally-oriented items and respondents' first language writing system direction.

          - This page will be updated with information as the study progresses. 
            
          ### To participate, please click on one of the following links below

          - [English instrument](https://unc.az1.qualtrics.com/jfe/form/SV_3KTJGwhI1PzsATk?Q_Language=EN)

          - [Arabic instrument](https://unc.az1.qualtrics.com/jfe/form/SV_3KTJGwhI1PzsATk?Q_Language=AR)

          ### Please share these links

    socialIcons:
        - name: github
          url: "https://github.com/jdmar3/dissertation"
#        - name: twitter
#          url: "https://twitter.com/jdmar3"
#        - name: RsS
#          url: "index.xml"

#    editPost:
#        URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
#        Text: "Suggest Changes" # edit text
#        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
